# Generated by Django 4.0 on 2022-01-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_playlistitem_playlist_videos_playlistitem_playlist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ['order', '-timestamp']},
        ),
        migrations.AddField(
            model_name='playlist',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playlist',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlists.playlist'),
        ),
    ]
