# Generated by Django 4.0 on 2022-01-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0013_alter_playlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
