# Generated by Django 4.0 on 2022-01-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0014_alter_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
