# Generated by Django 3.2.7 on 2022-01-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0017_alter_playlistrelated_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_playlists_playlist_related_+', through='playlists.PlayListRelated', to='playlists.PlayList'),
        ),
    ]
