# Generated by Django 4.0 on 2022-01-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0018_alter_playlist_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related', through='playlists.PlayListRelated', to='playlists.PlayList'),
        ),
    ]
