# Generated by Django 4.0 on 2021-12-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_name_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
