# Generated by Django 4.0 on 2021-12-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videoproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'Published Video', 'verbose_name_plural': 'Published Videos'},
        ),
    ]
