# Generated by Django 4.0 on 2021-12-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_delete_videoproxy_videopublishedproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Published'), ('DR', 'Draft')], default='DR', max_length=2),
        ),
    ]
